import { GoogleGenAI } from "@google/genai";

export const generateImageWithGemini = async (prompt: string): Promise<string> => {
  // Assume process.env.API_KEY is available in the environment
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: `A stunning, high-resolution, photorealistic design for a phone case. The design should feature: ${prompt}. Centered, vibrant, and visually appealing.`,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '9:16', // Common phone aspect ratio
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    throw new Error("Failed to generate AI image. Please try again.");
  }
};

export const generateDescriptionWithGemini = async (productName: string, category: string): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `Generate a short, engaging, and benefit-focused e-commerce product description for a phone case.
  - Product Name: "${productName}"
  - Category/Brand: "${category}"
  
  The description should be a single paragraph, approximately 20-30 words long. Focus on the style, vibe, and appeal. Do not use markdown, bullet points, or any special formatting. Just plain text.`;

  try {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });
    
    if (response.text) {
        return response.text.trim();
    } else {
        throw new Error("The AI did not return a description.");
    }
  } catch (error) {
    console.error("Error generating description with Gemini:", error);
    throw new Error("Failed to generate AI description. Please try again.");
  }
};
